name: Docker Publish

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    strategy:
      matrix:
        platform:
          - linux/386
          - linux/amd64
          - linux/arm/v6
          - linux/arm/v7
          - linux/arm64
          - linux/ppc64le
          - linux/s390x
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2.1.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}


      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2.1.0

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2.5.0
        with:
          buildkitd-flags: --debug
          install: true

      - name: Set up tags and labels
        id: meta
        uses: crazy-max/ghaction-docker-meta@v1
        with:
          images: youtube-dl
          tag-semver: |
            {{major}}.{{minor}}.{{patch}}
            {{major}}.{{minor}}
            {{major}}
          tag-sha: true

      - name: Multi-arch build
        uses: docker/build-push-action@v2
        with:
          cache-from: type=registry,ref=ghcr.io/djbender/youtube-dl:cache
          cache-to: type=registry,ref=ghcr.io/djbender/youtube-dl:cache,mode=max
          labels: ${{ steps.meta.outputs.labels }}
          load: ${{ matrix.platform == 'linux/amd64' }}
          platforms: ${{ matrix.platform }}
          tags: ${{ steps.meta.outputs.tags }}

      - name: Test
        env:
          IMAGE_ID: youtube-dl:${{ steps.meta.outputs.version }}
        if: matrix.platform == 'linux/amd64'
        run: ./test.sh

  push:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/')
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: Login to docker.io
        uses: docker/login-action@v1
        with:
          username: ${{ github.repository_owner }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2.1.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2.1.0

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2.5.0
        with:
          buildkitd-flags: --debug
          install: true

      - name: Set up tags and labels
        id: meta
        uses: crazy-max/ghaction-docker-meta@v1
        with:
          images: |
            djbender/youtube-dl
            ghcr.io/djbender/youtube-dl
          tag-semver: |
            {{major}}.{{minor}}.{{patch}}
            {{major}}.{{minor}}
            {{major}}
          tag-sha: true

      - name: Multi-arch build
        uses: docker/build-push-action@v2
        with:
          cache-from: type=registry,ref=ghcr.io/djbender/youtube-dl:cache
          cache-to: type=registry,ref=ghcr.io/djbender/youtube-dl:cache,mode=max
          platforms: linux/386,linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64,linux/ppc64le,linux/s390x
          push: true
          labels: ${{ steps.meta.outputs.labels }}
          tags: ${{ steps.meta.outputs.tags }}
